before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: C8/kOlp6MoYUT+ZfV9RlTc58cKw0nN9pDto3g6Wnh2iODXxPayUkyCgE9VmGVyTi+T7LzrSQpY9sQuxyFjRUxEsxDVJJsEz+EasCkGhjNyR2xUS12EQ2X6S3a5XhSXxHWVP8+uN/sOQJvsU/fmdMgyoAiFkR+FcHAmgykZ7d0vF6SGcvu2qqr/IzJ1zVw1G2gjb1D0p4Fha4MLIKC020+z0lgMvtx/sulqjOE/pZ5PJEWPMrEg+lv7Naun6ILEAGfn92BcdEaYoe+3TrMdEqTIKe2irZ94sQFeztaxUe2BWYJNCvZYCsgMywBUkw0tpgMdfj9+fUqGEA6keCmswN7sFJIiVLurmWnzzgxR77WFp3pFFSEaQuwShkRTxfoCv6my49TlRdbBl0dPV9KMU6stsLYFhyuYjTivUhZGDYDtdAIAJzlGps5jrKfe2fbrXzQgvn/sZxTMuXetcxPvmghUrTgXg69o5DocTFYPdHasVybdJlJI8GGsp1CRWEfjlleaNqS+B+B8nNGTFz4jJZ58dVnwphxGm/2y1eYJgchSwfGaPUdJlZjCJhlKFywDqtDhxMVRHeY4QI27GK5EAQPVxsAE2GKPw/EqhOVuxY7xS8+B8AEDOHDns3uy4VtgjTStseDQxjnSJ5zkfEaRyYzhgbZtMNY2LlzQ+VC0oxuxw= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
